---
- name: Fetch kubeconfig from server
  hosts: k3s_server
  become: true
  tasks:
    - name: Read kubeconfig
      ansible.builtin.slurp:
        src: /etc/rancher/k3s/k3s.yaml
      register: kc

    - name: Save to local ~/.kube/config (controller)
      delegate_to: localhost
      run_once: true
      vars:
        kube_dir: "{{ lookup('env','HOME') + '/.kube' }}"
      block:
        - name: Ensure ~/.kube exists
          ansible.builtin.file:
            path: "{{ kube_dir }}"
            state: directory
            mode: "0700"

        - name: Write config
          ansible.builtin.copy:
            dest: "{{ kube_dir }}/config"
            mode: "0600"
            content: "{{ kc.content | b64decode }}"

