---
- name: Kerberos + CIFS (user-ticket) mount for FlashArray share
  hosts: arch
  become: yes
  gather_facts: yes

  vars:
    realm_upper: "YOGURT.LAB"
    domain_lower: "yogurt.lab"
    smb_server: "nas01-yogurt.yogurt.lab"
    smb_share: "yogurt-smpexport1"
    mount_point: "/mnt/yogurt-smpexport1"

  pre_tasks:
    - name: Pick package names per distro
      set_fact:
        krb_pkgs: >-
          {{ (ansible_os_family == 'Debian') | ternary(['krb5-user','cifs-utils','keyutils'],
             (ansible_os_family == 'RedHat') | ternary(['krb5-workstation','cifs-utils','keyutils'],
             (ansible_os_family == 'Archlinux') | ternary(['krb5','cifs-utils','keyutils'],
             ['krb5-user','cifs-utils','keyutils']))) }}

  tasks:
    - name: Ensure Kerberos/CIFS packages are present
      package:
        name: "{{ krb_pkgs }}"
        state: present

    - name: Configure /etc/krb5.conf (DNS-based discovery; minimal + safe)
      copy:
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: "0644"
        content: |
          [libdefaults]
            default_realm = {{ realm_upper }}
            dns_lookup_kdc = true
            dns_lookup_realm = true
            rdns = false
            ticket_lifetime = 24h
            renew_lifetime  = 7d
            forwardable = true
          [realms]
            {{ realm_upper }} = {
              # leave empty to use DNS SRV (recommended)
            }
          [domain_realm]
            .{{ domain_lower }} = {{ realm_upper }}
            {{ domain_lower }} = {{ realm_upper }}

    - name: Create mount point
      file:
        path: "{{ mount_point }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Ensure fstab entry exists (Kerberos multiuser + systemd automount)
      mount:
        path: "{{ mount_point }}"
        src: "//{{ smb_server }}/{{ smb_share }}"
        fstype: cifs
        opts: "sec=krb5,vers=3.1.1,seal,_netdev,x-systemd.automount,noauto,mfsymlinks"
        state: present

    - name: Reload systemd units (for the new automount)
      command: systemctl daemon-reload
      changed_when: false

