# umount-cifs.yml
- hosts: archnode001
  become: yes
  tasks:
    - name: Unmount if mounted
      command: /usr/bin/umount /mnt/yogurt-smpexport1
      register: um
      failed_when: um.rc not in [0,32]     # rc=32: not mounted
      changed_when: um.rc == 0

    - name: Show mount status
      command: /usr/bin/findmnt -T /mnt/yogurt-smpexport1 || true
      changed_when: false

